---
title: "Meet Alex"
teaching: 5
exercises: 0
---

## Say hello to Alex!

Alex is a graduate student studying Music Psychology. Alex is a pianist, and also likes to dabble in music composition. Alex is comfortable using Ableton Live and Logic Pro with MIDI keystations to record and master music.

Alex also spent a summer interning at a Music Label. Responsibilities included entering data in an Excel spreadsheet, producing monthly reports with average duration of listens, most listened to tracks, and most popular artists, and visualising the results using bar graphs. Alex is comfortable carrying out these calculations in Excel, but has no experience doing these calculations using other statistical programmes.

As part of the PhD, Alex is investigating the effect of background music on individuals' working memory capacity. To do so, Alex ran a study where participants carried out a comprehension task and a working memory task, either in silence, or with background music. The study was run online, and data was collected using a Web-based survey tool. Alex has collected a sufficient number of responses, and now wants to download and analyse the data, to see whether background music had an effect on the participants' performances in the tasks. 

Alex wants to try using R within the RStudio environment to explore and visualise the collected data. Furthermore, Alex wants to document the work carried out, to make it easier to remember what was done when writing up the methodology of the dissertation.
